name: Update Guestbook

on:
  issues:
    types: [created, opened, edited, deleted]

permissions:
  contents: write
  issues: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get issue content
        id: guestbook
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const content = issue.data.body;
            const author = issue.data.user.login;
            const now = new Date().toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" });
            const entry = `- ðŸ—£ï¸ @${author}: ${content} _(enviado em ${now})_`;

            core.setOutput("entry", entry);

      - name: Update README.md
        run: |
          echo "${{ steps.guestbook.outputs.entry }}" >> GUESTBOOK.md
          cat GUESTBOOK.md > README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md GUESTBOOK.md
          git diff --cached --quiet || git commit -m ":sparkles: update guestbook"
          git push
